name: Docker Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      env:
        VARIABLE: "value"
      run: |
        echo "VARIABLE is $VARIABLE"
        docker build -t predictive-maintenance-api .
        
    - name: Run container and test API
      run: |
        docker run -d --name pm_api -p 8000:8000 predictive-maintenance-api
        sleep 10
        # Show logs if the container isn't up
        docker logs pm_api || true
        # Attempt to curl the API
        curl --fail http://localhost:8000/ || exit 1
